NativeTurkish.Web/Areas/Member/Controllers/ChatController.cs
using Microsoft.AspNetCore.Mvc;
using NativeTurkish.Web.CustomFilters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NativeTurkish.Web.Areas.Member.Controllers
{
    [Area("Member")]
    [JwtAuthorize(Roles ="Admin,Member")]
    public class ChatController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

NativeTurkish.Web/Areas/Member/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{
    string active = string.Empty;
    if (TempData["Active"] != null)
    {
        active = TempData["Active"]?.ToString();
    }
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FactoryWeb</title>
    <link rel="stylesheet" type="text/css" href="/lib/twitter-bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/memberlayout.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i%7COpen+Sans:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">
    <style>
        body {
            font-family: 'Montserrat';
            font-size: 14px;
        }
    </style>
    @RenderSection("Styles", false)

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" asp-action="Index" asp-controller="Home" asp-area="Member">Native Turkish</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link @(active=="question"?"active":"")" asp-action="Index" asp-controller="Question">Soru Çöz</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link @(active=="chat"?"active":"")" asp-action="Index" asp-controller="Chat">Rastgele birisiyle Konuş!</a>
                </li>
            </ul>
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle @(active=="profile"?"active":"")" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-user fa-fw"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" asp-area="Member" asp-controller="Profile" asp-action="Index">@HttpContextAccessor.HttpContext.Session.GetString("name")</a>
                        <a class="dropdown-item" asp-area="" asp-controller="Auth" asp-action="LogOut"><i class="fas fa-sign-out-alt mr-2"></i>ÇıkışYap</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container pt-3">
        @RenderBody()
    </div>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/twitter-bootstrap/js/popper.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script>
        $(document).ready(function () {
            $('ul.nav li.dropdown').hover(function () {
                $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeIn(200);
            }, function () {
                $(this).find('.dropdown-menu').stop(true, true).delay(200).fadeOut(200);
            });
        });
    </script>
    @RenderSection("Javascript", false)
</body>
</html>